bundler_args: --binstubs
language: ruby
notifications:
  email:
    recipients:
      - noel@peden.biz
    on_success: always
env:
  - RAILS_VERSION=3.2
  - RAILS_VERSION=4.0  
rvm:
  - 1.9.3
  - 2.0.0
script:
  spec/ci.sh
